### ISSUE TITLE
Emit typescript declaration

### ISSUE THREAD

**Issue by seaneking** [cibernox/svelte-media#3]
Hey thanks for the great plugin! I see it's written in typescript, but no declaration file is emitted so importing it into a ts project complains. Should just be a matter of adding `emitDeclaration` or `emitDeclarationOnly` to the `tsconfig`?

**Comment by bryanmylee** [comment]
Bump! Would love to have TypeScript definitions for this library. Do let me know if you need help setting it up!

**Comment by bryanmylee** [comment]
For those who need a temporary solution, create a `svelte-media.d.ts` somewhere in your project and add this module declaration:

```typescript
declare module 'svelte-media' {
  import type { Readable } from 'svelte/store';
  function watchMedia<Query>(
    queries: { [K in keyof Query]: string }
  ): Readable<{ [K in keyof Query]: boolean }>;
  export default watchMedia;
}
```

**Comment by cibernox** [comment]
I’ll try to find some time this weekend to work on that. It would certainly be handy

**Comment by cibernox** [comment]
Ok, I'll revamped the build system to use typescript 4 and output styles.
I released it as 0.1 as there are significant changes, in case it breaks something. Try it and let me know if it works for you.

**Comment by bryanmylee** [comment]
With `svelte-media@latest`, I'm getting the following error on my project:

```
Cannot find module 'svelte-media' or its corresponding type declarations.ts(2307)
```

**Comment by cibernox** [comment]
@bryanmylee try 0.1.3, I think it should be fixed again. I tested on my sveltekit projects with ssr enabled.

**Comment by madeleineostoja** [comment]
Still broken for me, and now the whole import is broken (`watchMedia` is not a function` when building)

**Comment by cibernox** [comment]
What build tool do you use? Sveltekit? Rollup? Webpack? I works for me with sveltekit/vite

**Comment by madeleineostoja** [comment]
Sveltekit with the static adapter, it’s the build that fails, development works fine

**Comment by cibernox** [comment]
@madeleineostoja I didn't try a production build, I can see the error.

I just released 0.1.4 which seems to work for me on both dev and prod.

**Comment by madeleineostoja** [comment]
Seems to work! Would be great if the `watchMedia` function returned a proper type map of the media query values with a `boolean` type, rather than just a `{}` type. But that's an improvement for another day I guess
